name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        make init

    - name: Run tests
      run: |
        make run

    - name: Build Docker image
      run: |
        make build
